# MyPyEigen Comprehensive Tests

在本Notebook中，我们将会测试：
- `matmult`: 矩阵乘法
- `append`: 在2D矩阵行/列方向拼接
- `concat`: 一次性拼接多个2D矩阵
- `inner`: 1D向量内积
- `outer`: 1D向量外积
- `rot90`: 矩阵旋转

In [2]:
import MyPyEigen as pe
import numpy as np

## 1. Test matmult

In [2]:
# 1) Test matmult
print("=== Test matmult ===")
A = np.array([[1,2],[3,4]], dtype=float)
B = np.array([[5,6],[7,8]], dtype=float)
C = pe.matmult(A, B)
expectedC = A @ B
print("A=\n", A)
print("B=\n", B)
print("C=matmult(A,B)=\n", C)
assert C.shape == (2,2)
assert np.allclose(C, expectedC), "matmult result mismatch"
print("[OK] matmult normal case passed.")

# Test matmult dimension mismatch
A_mis = np.array([[1,2,3],[4,5,6]], dtype=float)  # shape(2,3)
B_mis = np.array([[7,8],[9,10]], dtype=float)     # shape(2,2)
try:
    _ = pe.matmult(A_mis, B_mis)
    raise AssertionError("Expected dimension mismatch for matmult, but no exception thrown!")
except ValueError as e:
    print("[OK] Caught matmult dimension mismatch exception:", e)

=== Test matmult ===
A=
 [[1. 2.]
 [3. 4.]]
B=
 [[5. 6.]
 [7. 8.]]
C=matmult(A,B)=
 [[19. 22.]
 [43. 50.]]
[OK] matmult normal case passed.
[OK] Caught matmult dimension mismatch exception: matmult(): Dimension mismatch. A.cols() must match B.rows().


## 2. Test Append

In [3]:
# 2) Test append
print("\n=== Test append ===")
X = np.array([[1,2],[3,4]], dtype=float)
Y = np.array([[5,6],[7,8]], dtype=float)

# axis=0 => row-wise
app0 = pe.append(X, Y, 0)
expected0 = np.vstack([X,Y])
print("row-wise append(X,Y):\n", app0)
assert app0.shape == (4,2)
assert np.allclose(app0, expected0)

# axis=1 => col-wise
app1 = pe.append(X, Y, 1)
expected1 = np.hstack([X,Y])
print("col-wise append(X,Y):\n", app1)
assert app1.shape == (2,4)
assert np.allclose(app1, expected1)

# mismatch
Z = np.array([[9,10,11],[12,13,14]], dtype=float)  # shape(2,3)
try:
    _ = pe.append(X, Z, 0)  # row-wise => need same cols, but 2 vs 3
    raise AssertionError("Expected mismatch for append, but no exception thrown!")
except ValueError as e:
    print("[OK] Caught append mismatch:", e)
print("[OK] append tests passed.")




=== Test append ===
row-wise append(X,Y):
 [[1. 2.]
 [3. 4.]
 [5. 6.]
 [7. 8.]]
col-wise append(X,Y):
 [[1. 2. 5. 6.]
 [3. 4. 7. 8.]]
[OK] Caught append mismatch: append(): dimension mismatch for row-wise concatenation
[OK] append tests passed.


## 3. Test Concat

In [4]:
# 3) Test concat
print("\n=== Test concat ===")
A2 = np.array([[1,2],[3,4]], dtype=float)
B2 = np.array([[5,6],[7,8]], dtype=float)
C2 = np.array([[9,10],[11,12]], dtype=float)

# axis=0 => row-wise
out0 = pe.concat([A2,B2,C2], 0)
expected0 = np.vstack([A2,B2,C2])
print("concat axis=0 =>\n", out0)
assert np.allclose(out0, expected0)

# axis=1 => col-wise
out1 = pe.concat([A2,B2,C2], 1)
expected1 = np.hstack([A2,B2,C2])
print("concat axis=1 =>\n", out1)
assert np.allclose(out1, expected1)

# mismatch
D2 = np.array([[13,14,15],[16,17,18]], dtype=float) # shape(2,3)
try:
    _ = pe.concat([A2,B2,D2], 0)  # row-wise => need same cols=2, but D2 has 3
    raise AssertionError("Expected mismatch for concat, but no exception thrown!")
except ValueError as e:
    print("[OK] Caught concat mismatch:", e)
print("[OK] concat tests passed.")



=== Test concat ===
concat axis=0 =>
 [[ 1.  2.]
 [ 3.  4.]
 [ 5.  6.]
 [ 7.  8.]
 [ 9. 10.]
 [11. 12.]]
concat axis=1 =>
 [[ 1.  2.  5.  6.  9. 10.]
 [ 3.  4.  7.  8. 11. 12.]]
[OK] Caught concat mismatch: concat(): dimension mismatch on cols for row-wise concatenation
[OK] concat tests passed.


## 4. Test Inner

In [5]:
# 4) Test inner (dot product)
print("\n=== Test inner ===")
v1 = np.array([1.0,2.0,3.0], dtype=float)
v2 = np.array([4.0,5.0,6.0], dtype=float)
res_inner = pe.inner(v1, v2)
expected_inner = np.dot(v1, v2)
print("v1 dot v2 =", res_inner)
assert abs(res_inner - expected_inner) < 1e-12

# mismatch
try:
    pe.inner(v1, np.array([7.0,8.0]))
    raise AssertionError("Expected mismatch for inner, but no exception thrown!")
except ValueError as e:
    print("[OK] Caught inner mismatch:", e)
print("[OK] inner test passed.")



=== Test inner ===
v1 dot v2 = 32.0
[OK] Caught inner mismatch: inner(): vectors must have the same size
[OK] inner test passed.


## 5. Test Outer.

In [6]:
# 5) Test outer
print("\n=== Test outer ===")
v3 = np.array([1.0, 2.0], dtype=float)
v4 = np.array([10.0,20.0,30.0], dtype=float)
res_outer = pe.outer(v3, v4)
expected_outer = np.outer(v3, v4)
print("outer:\n", res_outer)
assert res_outer.shape == (2,3)
assert np.allclose(res_outer, expected_outer)
print("[OK] outer test passed.")


=== Test outer ===
outer:
 [[10. 20. 30.]
 [20. 40. 60.]]
[OK] outer test passed.


## 6. Test Rot90

In [7]:
# 6) Test rot90
print("\n=== Test rot90 ===")
M = np.array([
    [1,2,3],
    [4,5,6]
], dtype=float)
# shape(2,3)
r1 = pe.rot90(M, 1)
expected_r1 = np.array([
    [4,1],
    [5,2],
    [6,3]
], dtype=float)
print("rot90(M,1)=\n", r1)
assert r1.shape == (3,2)
assert np.allclose(r1, expected_r1)

# k=2
r2 = pe.rot90(M, 2)
expected_r2 = np.array([
    [6,5,4],
    [3,2,1]
], dtype=float)
assert np.allclose(r2, expected_r2)

# negative k => e.g. k=-1 => same as k=3
r_neg = pe.rot90(M, -1)
expected_r3 = np.array([
    [3,6],
    [2,5],
    [1,4]
], dtype=float)
assert np.allclose(r_neg, expected_r3)
print("[OK] rot90 tests passed.")

print("\n=== All Tests Done ===")
print("If no error above, MyPyEigen is working correctly!")



=== Test rot90 ===
rot90(M,1)=
 [[4. 1.]
 [5. 2.]
 [6. 3.]]
[OK] rot90 tests passed.

=== All Tests Done ===
If no error above, MyPyEigen is working correctly!


## Benchmarking the runtime

我们来比较一下我自己写的MyPyEigen和numpy哪一个更快一些，嘿嘿

In [8]:
import timeit
import functools

def timeit_decorator(n=1000):
    """ 使用 timeit 运行 n 次，计算平均运行时间 """
    def decorator(func):
        @functools.wraps(func)
        def wrapper(*args, **kwargs):
            execution_time = timeit.timeit(lambda: func(*args, **kwargs), number=n) / n
            print(f"{func.__name__} 平均运行时间 (timeit): {execution_time:.9f} 秒")
            return func(*args, **kwargs)
        return wrapper
    return decorator

@timeit_decorator(n=10000)
def fast_function():
    return sum(range(10))

fast_function()


fast_function 平均运行时间 (timeit): 0.000000479 秒


45

In [13]:
def timeit_decorator(n=10000):
    """ 使用 timeit 运行 n 次，计算平均运行时间 """
    def decorator(func):
        @functools.wraps(func)
        def wrapper(*args, **kwargs):
            execution_time = timeit.timeit(lambda: func(*args, **kwargs), number=n) / n
            print(f"{func.__name__} 平均运行时间 (timeit): {execution_time:.9f} 秒")
            return func(*args, **kwargs)
        return wrapper
    return decorator

# 创建测试函数
@timeit_decorator(n=10000)
def pe_rot90():
    M = np.random.rand(1000, 1000)  # 生成随机 100x100 矩阵
    pe.rot90(M, 1)  # 旋转 90°

@timeit_decorator(n=10000)
def np_rot90():
    M = np.random.rand(1000, 1000)  # 生成随机 100x100 矩阵
    np.rot90(M, 1)  # 旋转 90°

# 运行测试
pe_rot90()
np_rot90()

pe_rot90 平均运行时间 (timeit): 0.008489861 秒
np_rot90 平均运行时间 (timeit): 0.003828284 秒


In [ ]:
@timeit_decorator(n=10000)
def test_rotation():
    M = np.random.rand(100, 100)  # 生成随机 100x100 矩阵
    pe.rot90(M, 1)  # 旋转 90°

# 运行测试
test_rotation()

In [4]:
# %% [markdown]
# # MyPyEigen Comprehensive Tests and Benchmark
# 
# 本 Notebook 用于测试 MyPyEigen 模块中实现的以下功能：
# - `matmult`: 矩阵乘法 (等效于 NumPy 的 @ 运算符)
# - `append`: 在2D矩阵行/列方向拼接
# - `concat`: 一次性拼接多个2D矩阵
# - `inner`: 1D 向量内积
# - `outer`: 1D 向量外积
# - `rot90`: 矩阵旋转
# 
# 同时，也包含 Benchmark 部分，用于比较 MyPyEigen 中 `rot90` 与 NumPy 自带 `np.rot90` 的性能。
# 
# 确保已经通过 `pip install .`（在 bindings 目录下运行）安装了 MyPyEigen，并且能够通过以下方式导入：
# 
# ```python
# import mypyeigen as pe
# ```
# 
# 注意：本 Notebook 中异常测试部分要求相关函数在维度不匹配时抛出 ValueError（我们已修改为 ValueError）。

# %% [code]
import MyPyEigen as pe
import numpy as np
import timeit, functools

# %% [markdown]
# ## 1. Test matmult
# 
# 测试矩阵乘法函数 `matmult`，包括正常运算和维度不匹配的异常情况。

# %% [code]
print("=== Test matmult ===")
A = np.array([[1, 2],
              [3, 4]], dtype=float)
B = np.array([[5, 6],
              [7, 8]], dtype=float)
C = pe.matmult(A, B)
expectedC = A @ B
print("A =\n", A)
print("B =\n", B)
print("C = matmult(A,B) =\n", C)
assert C.shape == (2,2), "matmult: Shape mismatch."
assert np.allclose(C, expectedC), "matmult: Result mismatch."

# 维度不匹配测试
A_mis = np.array([[1, 2, 3],
                  [4, 5, 6]], dtype=float)  # shape (2,3)
B_mis = np.array([[7, 8],
                  [9,10]], dtype=float)    # shape (2,2)
try:
    _ = pe.matmult(A_mis, B_mis)
    raise AssertionError("matmult: Expected dimension mismatch exception, but none thrown!")
except ValueError as e:
    print("[OK] Caught matmult dimension mismatch exception:", e)
print("[OK] matmult tests passed.")

# %% [markdown]
# ## 2. Test append
# 
# 测试 `append` 函数：包括行拼接 (axis=0) 和列拼接 (axis=1)，以及维度不匹配的异常情况。

# %% [code]
print("\n=== Test append ===")
X = np.array([[1,2],
              [3,4]], dtype=float)
Y = np.array([[5,6],
              [7,8]], dtype=float)

# Row-wise append (axis=0)
app0 = pe.append(X, Y, 0)
expected0 = np.vstack([X, Y])
print("Row-wise append(X, Y):\n", app0)
assert app0.shape == (4,2), "append (axis=0): Shape mismatch."
assert np.allclose(app0, expected0), "append (axis=0): Result mismatch."

# Column-wise append (axis=1)
app1 = pe.append(X, Y, 1)
expected1 = np.hstack([X, Y])
print("Column-wise append(X, Y):\n", app1)
assert app1.shape == (2,4), "append (axis=1): Shape mismatch."
assert np.allclose(app1, expected1), "append (axis=1): Result mismatch."

# Mismatch test: 构造一个列数不同的矩阵
Z = np.array([[9,10,11],
              [12,13,14]], dtype=float)  # shape (2,3) vs X (2,2)
try:
    _ = pe.append(X, Z, 0)
    raise AssertionError("append: Expected dimension mismatch exception, but none thrown!")
except ValueError as e:
    print("[OK] Caught append dimension mismatch:", e)
print("[OK] append tests passed.")

# %% [markdown]
# ## 3. Test concat
# 
# 测试 `concat` 函数：一次性拼接多个矩阵，验证 row-wise 和 col-wise 拼接及异常情况。

# %% [code]
print("\n=== Test concat ===")
A2 = np.array([[1,2],[3,4]], dtype=float)
B2 = np.array([[5,6],[7,8]], dtype=float)
C2 = np.array([[9,10],[11,12]], dtype=float)

# Row-wise concat (axis=0)
out0 = pe.concat([A2, B2, C2], 0)
expected0 = np.vstack([A2, B2, C2])
print("concat axis=0:\n", out0)
assert np.allclose(out0, expected0), "concat (axis=0): Result mismatch."

# Column-wise concat (axis=1)
out1 = pe.concat([A2, B2, C2], 1)
expected1 = np.hstack([A2, B2, C2])
print("concat axis=1:\n", out1)
assert np.allclose(out1, expected1), "concat (axis=1): Result mismatch."

# Mismatch test: 构造一个矩阵维度不同的情况
D2 = np.array([[13,14,15],
               [16,17,18]], dtype=float)  # shape (2,3) vs A2 (2,2)
try:
    _ = pe.concat([A2, B2, D2], 0)  # row-wise：要求所有矩阵列数一致
    raise AssertionError("concat: Expected dimension mismatch exception, but none thrown!")
except ValueError as e:
    print("[OK] Caught concat dimension mismatch:", e)
print("[OK] concat tests passed.")

# %% [markdown]
# ## 4. Test inner
# 
# 测试 `inner` 函数：计算 1D 向量的内积，同时验证尺寸不匹配时抛出异常。

# %% [code]
print("\n=== Test inner ===")
v1 = np.array([1.0, 2.0, 3.0], dtype=float)
v2 = np.array([4.0, 5.0, 6.0], dtype=float)
res_inner = pe.inner(v1, v2)
expected_inner = np.dot(v1, v2)
print("inner(v1, v2) =", res_inner)
assert abs(res_inner - expected_inner) < 1e-12, "inner: Result mismatch."

# Mismatch test for inner
try:
    pe.inner(v1, np.array([7.0, 8.0], dtype=float))
    raise AssertionError("inner: Expected dimension mismatch exception, but none thrown!")
except ValueError as e:
    print("[OK] Caught inner dimension mismatch:", e)
print("[OK] inner tests passed.")

# %% [markdown]
# ## 5. Test outer
# 
# 测试 `outer` 函数：计算 1D 向量的外积，并验证结果与 NumPy 的 np.outer 一致。

# %% [code]
print("\n=== Test outer ===")
v3 = np.array([1.0, 2.0], dtype=float)
v4 = np.array([10.0, 20.0, 30.0], dtype=float)
res_outer = pe.outer(v3, v4)
expected_outer = np.outer(v3, v4)
print("outer(v3, v4):\n", res_outer)
assert res_outer.shape == (2, 3), "outer: Shape mismatch."
assert np.allclose(res_outer, expected_outer), "outer: Result mismatch."
print("[OK] outer tests passed.")

# %% [markdown]
# ## 6. Test rot90
# 
# 测试 `rot90` 函数：验证旋转90度的各种情况（包括正负 k）。

# %% [code]
print("\n=== Test rot90 ===")
M = np.array([[1,2,3],
              [4,5,6]], dtype=float)
# k=1 -> 90° clockwise, 预期结果：
expected_r1 = np.array([[4,1],
                        [5,2],
                        [6,3]], dtype=float)
r1 = pe.rot90(M, 1)
print("rot90(M, 1)=\n", r1)
assert r1.shape == (3,2)
assert np.allclose(r1, expected_r1), "rot90 (k=1) result mismatch."

# k=2 -> 180°
expected_r2 = np.array([[6,5,4],
                        [3,2,1]], dtype=float)
r2 = pe.rot90(M, 2)
assert r2.shape == (2,3)
assert np.allclose(r2, expected_r2), "rot90 (k=2) result mismatch."

# k=3 -> 270° clockwise, 预期结果 (等价于 90° counter-clockwise)：
expected_r3 = np.array([[3,6],
                        [2,5],
                        [1,4]], dtype=float)
r3 = pe.rot90(M, 3)
assert r3.shape == (3,2)
assert np.allclose(r3, expected_r3), "rot90 (k=3) result mismatch."

# 测试负数 k: k = -1 应该等价于 k = 3
r_neg = pe.rot90(M, -1)
assert np.allclose(r_neg, expected_r3), "rot90 (k=-1) result mismatch."
print("[OK] rot90 tests passed.")

# %% [markdown]
# ## 7. Benchmarking (Example)
# 
# 使用 timeit 对比 MyPyEigen 中 rot90 与 NumPy 的 np.rot90 的运行时间。
# 注意：由于 Python 调用 C++ 扩展开销较小，此测试主要反映两者计算部分的差异。
# 我们对一个 1000x1000 的随机矩阵进行 90°旋转，并取平均时间。

# %% [code]
def benchmark(func, *args, number=100):
    t = timeit.timeit(lambda: func(*args), number=number)
    return t / number

# 生成一个 1000x1000 的随机矩阵
M_large = np.random.rand(1000, 1000)

# Benchmark MyPyEigen.rot90
time_pe = benchmark(pe.rot90, M_large, 1, number=100)
print("MyPyEigen.rot90 average time: {:.9f} seconds".format(time_pe))

# Benchmark NumPy's np.rot90
time_np = benchmark(np.rot90, M_large, 1, number=100)
print("np.rot90 average time: {:.9f} seconds".format(time_np))

# %% [markdown]
# # All Tests and Benchmarks Completed
# 
# 如果所有断言都通过且 benchmark 输出合理，说明 MyPyEigen 的各个接口工作正常并且性能可接受！


=== Test matmult ===
A =
 [[1. 2.]
 [3. 4.]]
B =
 [[5. 6.]
 [7. 8.]]
C = matmult(A,B) =
 [[19. 22.]
 [43. 50.]]
[OK] Caught matmult dimension mismatch exception: matmult(): Dimension mismatch. A.cols() must match B.rows().
[OK] matmult tests passed.

=== Test append ===
Row-wise append(X, Y):
 [[1. 2.]
 [3. 4.]
 [5. 6.]
 [7. 8.]]
Column-wise append(X, Y):
 [[1. 2. 5. 6.]
 [3. 4. 7. 8.]]
[OK] Caught append dimension mismatch: append(): dimension mismatch for row-wise concatenation
[OK] append tests passed.

=== Test concat ===
concat axis=0:
 [[ 1.  2.]
 [ 3.  4.]
 [ 5.  6.]
 [ 7.  8.]
 [ 9. 10.]
 [11. 12.]]
concat axis=1:
 [[ 1.  2.  5.  6.  9. 10.]
 [ 3.  4.  7.  8. 11. 12.]]
[OK] Caught concat dimension mismatch: concat(): dimension mismatch on cols for row-wise concatenation
[OK] concat tests passed.

=== Test inner ===
inner(v1, v2) = 32.0
[OK] Caught inner dimension mismatch: inner(): vectors must have the same size
[OK] inner tests passed.

=== Test outer ===
outer(v3, v4):
 [[10

In [6]:
# %% [code]
import MyPyEigen as pe
import numpy as np
import timeit, functools

def benchmark_function(func, args, number=10):
    """
    使用 timeit 运行 func(*args) 指定次数，并返回平均执行时间（秒）
    """
    return timeit.timeit(lambda: func(*args), number=number) / number

# 测试矩阵规模列表：从小到大
matrix_sizes = [10, 50, 100, 500, 1000]

# 记录各个函数的 benchmark 结果，结果格式： (size, MyPyEigen_time, NumPy_time)
results = {}

# Benchmark Matrix Multiplication (matmult)
results["matmult"] = []
for size in matrix_sizes:
    A = np.random.rand(size, size)
    B = np.random.rand(size, size)
    t_pe = benchmark_function(pe.matmult, (A, B), number=10)
    # NumPy: 使用 @ 运算符
    t_np = benchmark_function(lambda A, B: A @ B, (A, B), number=10)
    results["matmult"].append((size, t_pe, t_np))

# Benchmark Append (row-wise)
results["append"] = []
for size in matrix_sizes:
    X = np.random.rand(size, size)
    Y = np.random.rand(size, size)
    t_pe = benchmark_function(pe.append, (X, Y, 0), number=10)
    # NumPy: 使用 vstack 实现行拼接
    t_np = benchmark_function(lambda X, Y: np.vstack([X, Y]), (X, Y), number=10)
    results["append"].append((size, t_pe, t_np))

# Benchmark Concat (row-wise) --- 假设 concat 接口接收一个列表
results["concat"] = []
for size in matrix_sizes:
    # 构造三个相同尺寸的矩阵
    A = np.random.rand(size, size)
    B = np.random.rand(size, size)
    C = np.random.rand(size, size)
    mats = [A, B, C]
    t_pe = benchmark_function(pe.concat, (mats, 0), number=10)
    t_np = benchmark_function(lambda mats: np.vstack(mats), (mats,), number=10)
    results["concat"].append((size, t_pe, t_np))

# Benchmark Inner (1D vector dot product)
results["inner"] = []
for size in matrix_sizes:
    v1 = np.random.rand(size)
    v2 = np.random.rand(size)
    t_pe = benchmark_function(pe.inner, (v1, v2), number=10000)
    t_np = benchmark_function(lambda v1, v2: np.dot(v1, v2), (v1, v2), number=10000)
    results["inner"].append((size, t_pe, t_np))

# Benchmark Outer (1D vector outer product)
results["outer"] = []
for size in matrix_sizes:
    v1 = np.random.rand(size)
    # 为避免 v4 为0 维时出错，取长度为 max(1, size//2)
    v4_length = max(1, size // 2)
    v2 = np.random.rand(v4_length)
    t_pe = benchmark_function(pe.outer, (v1, v2), number=10000)
    t_np = benchmark_function(lambda v1, v2: np.outer(v1, v2), (v1, v2), number=10000)
    results["outer"].append((size, t_pe, t_np))

# Benchmark Rot90 (2D matrix rotation)
results["rot90"] = []
for size in matrix_sizes:
    M = np.random.rand(size, size)
    t_pe = benchmark_function(pe.rot90, (M, 1), number=100)
    t_np = benchmark_function(lambda M: np.rot90(M, 1), (M,), number=100)
    results["rot90"].append((size, t_pe, t_np))

# 打印 Benchmark 结果
print("Benchmark Results (Average time in seconds):")
for func_name, data in results.items():
    print(f"\nFunction: {func_name}")
    print("Matrix/Vector Size\tMyPyEigen\t\tNumPy")
    for size, t_pe, t_np in data:
        print(f"{size}\t\t\t{t_pe:.9f}\t\t{t_np:.9f}")

# %% [markdown]
# ## Benchmark Analysis
# 
# 以上结果显示了在不同规模下，MyPyEigen 和 NumPy 的运行时间差异。你可以进一步记录这些数据到报告中，
# 分析在小规模和大规模矩阵下，C++ (Eigen) 与 NumPy 的性能特点及优劣。


Benchmark Results (Average time in seconds):

Function: matmult
Matrix/Vector Size	MyPyEigen		NumPy
10			0.000004108		0.000003088
50			0.000018842		0.000027579
100			0.000149904		0.000023333
500			0.008530704		0.001018100
1000			0.053713771		0.008749083

Function: append
Matrix/Vector Size	MyPyEigen		NumPy
10			0.000002592		0.000004692
50			0.000040083		0.000002379
100			0.000042183		0.000004550
500			0.001470279		0.000216246
1000			0.006305858		0.001229717

Function: concat
Matrix/Vector Size	MyPyEigen		NumPy
10			0.000002658		0.000002175
50			0.000043304		0.000002742
100			0.000045283		0.000005775
500			0.002830300		0.000340500
1000			0.013430517		0.002082908

Function: inner
Matrix/Vector Size	MyPyEigen		NumPy
10			0.000001023		0.000000435
50			0.000001006		0.000000453
100			0.000001037		0.000000494
500			0.000001102		0.000000532
1000			0.000001413		0.000000574

Function: outer
Matrix/Vector Size	MyPyEigen		NumPy
10			0.000001464		0.000001457
50			0.000001994		0.000002119
100			0.00