# MyPyEigen Comprehensive Tests

在本Notebook中，我们将会测试：
- `matmult`: 矩阵乘法
- `append`: 在2D矩阵行/列方向拼接
- `concat`: 一次性拼接多个2D矩阵
- `inner`: 1D向量内积
- `outer`: 1D向量外积
- `rot90`: 矩阵旋转

In [2]:
import MyPyEigen as pe
import numpy as np

## 1. Test matmult

In [2]:
# 1) Test matmult
print("=== Test matmult ===")
A = np.array([[1,2],[3,4]], dtype=float)
B = np.array([[5,6],[7,8]], dtype=float)
C = pe.matmult(A, B)
expectedC = A @ B
print("A=\n", A)
print("B=\n", B)
print("C=matmult(A,B)=\n", C)
assert C.shape == (2,2)
assert np.allclose(C, expectedC), "matmult result mismatch"
print("[OK] matmult normal case passed.")

# Test matmult dimension mismatch
A_mis = np.array([[1,2,3],[4,5,6]], dtype=float)  # shape(2,3)
B_mis = np.array([[7,8],[9,10]], dtype=float)     # shape(2,2)
try:
    _ = pe.matmult(A_mis, B_mis)
    raise AssertionError("Expected dimension mismatch for matmult, but no exception thrown!")
except ValueError as e:
    print("[OK] Caught matmult dimension mismatch exception:", e)

=== Test matmult ===
A=
 [[1. 2.]
 [3. 4.]]
B=
 [[5. 6.]
 [7. 8.]]
C=matmult(A,B)=
 [[19. 22.]
 [43. 50.]]
[OK] matmult normal case passed.
[OK] Caught matmult dimension mismatch exception: matmult(): Dimension mismatch. A.cols() must match B.rows().


## 2. Test Append

In [3]:
# 2) Test append
print("\n=== Test append ===")
X = np.array([[1,2],[3,4]], dtype=float)
Y = np.array([[5,6],[7,8]], dtype=float)

# axis=0 => row-wise
app0 = pe.append(X, Y, 0)
expected0 = np.vstack([X,Y])
print("row-wise append(X,Y):\n", app0)
assert app0.shape == (4,2)
assert np.allclose(app0, expected0)

# axis=1 => col-wise
app1 = pe.append(X, Y, 1)
expected1 = np.hstack([X,Y])
print("col-wise append(X,Y):\n", app1)
assert app1.shape == (2,4)
assert np.allclose(app1, expected1)

# mismatch
Z = np.array([[9,10,11],[12,13,14]], dtype=float)  # shape(2,3)
try:
    _ = pe.append(X, Z, 0)  # row-wise => need same cols, but 2 vs 3
    raise AssertionError("Expected mismatch for append, but no exception thrown!")
except ValueError as e:
    print("[OK] Caught append mismatch:", e)
print("[OK] append tests passed.")




=== Test append ===
row-wise append(X,Y):
 [[1. 2.]
 [3. 4.]
 [5. 6.]
 [7. 8.]]
col-wise append(X,Y):
 [[1. 2. 5. 6.]
 [3. 4. 7. 8.]]
[OK] Caught append mismatch: append(): dimension mismatch for row-wise concatenation
[OK] append tests passed.


## 3. Test Concat

In [4]:
# 3) Test concat
print("\n=== Test concat ===")
A2 = np.array([[1,2],[3,4]], dtype=float)
B2 = np.array([[5,6],[7,8]], dtype=float)
C2 = np.array([[9,10],[11,12]], dtype=float)

# axis=0 => row-wise
out0 = pe.concat([A2,B2,C2], 0)
expected0 = np.vstack([A2,B2,C2])
print("concat axis=0 =>\n", out0)
assert np.allclose(out0, expected0)

# axis=1 => col-wise
out1 = pe.concat([A2,B2,C2], 1)
expected1 = np.hstack([A2,B2,C2])
print("concat axis=1 =>\n", out1)
assert np.allclose(out1, expected1)

# mismatch
D2 = np.array([[13,14,15],[16,17,18]], dtype=float) # shape(2,3)
try:
    _ = pe.concat([A2,B2,D2], 0)  # row-wise => need same cols=2, but D2 has 3
    raise AssertionError("Expected mismatch for concat, but no exception thrown!")
except ValueError as e:
    print("[OK] Caught concat mismatch:", e)
print("[OK] concat tests passed.")



=== Test concat ===
concat axis=0 =>
 [[ 1.  2.]
 [ 3.  4.]
 [ 5.  6.]
 [ 7.  8.]
 [ 9. 10.]
 [11. 12.]]
concat axis=1 =>
 [[ 1.  2.  5.  6.  9. 10.]
 [ 3.  4.  7.  8. 11. 12.]]
[OK] Caught concat mismatch: concat(): dimension mismatch on cols for row-wise concatenation
[OK] concat tests passed.


## 4. Test Inner

In [5]:
# 4) Test inner (dot product)
print("\n=== Test inner ===")
v1 = np.array([1.0,2.0,3.0], dtype=float)
v2 = np.array([4.0,5.0,6.0], dtype=float)
res_inner = pe.inner(v1, v2)
expected_inner = np.dot(v1, v2)
print("v1 dot v2 =", res_inner)
assert abs(res_inner - expected_inner) < 1e-12

# mismatch
try:
    pe.inner(v1, np.array([7.0,8.0]))
    raise AssertionError("Expected mismatch for inner, but no exception thrown!")
except ValueError as e:
    print("[OK] Caught inner mismatch:", e)
print("[OK] inner test passed.")



=== Test inner ===
v1 dot v2 = 32.0
[OK] Caught inner mismatch: inner(): vectors must have the same size
[OK] inner test passed.


## 5. Test Outer.

In [6]:
# 5) Test outer
print("\n=== Test outer ===")
v3 = np.array([1.0, 2.0], dtype=float)
v4 = np.array([10.0,20.0,30.0], dtype=float)
res_outer = pe.outer(v3, v4)
expected_outer = np.outer(v3, v4)
print("outer:\n", res_outer)
assert res_outer.shape == (2,3)
assert np.allclose(res_outer, expected_outer)
print("[OK] outer test passed.")


=== Test outer ===
outer:
 [[10. 20. 30.]
 [20. 40. 60.]]
[OK] outer test passed.


## 6. Test Rot90

In [7]:
# 6) Test rot90
print("\n=== Test rot90 ===")
M = np.array([
    [1,2,3],
    [4,5,6]
], dtype=float)
# shape(2,3)
r1 = pe.rot90(M, 1)
expected_r1 = np.array([
    [4,1],
    [5,2],
    [6,3]
], dtype=float)
print("rot90(M,1)=\n", r1)
assert r1.shape == (3,2)
assert np.allclose(r1, expected_r1)

# k=2
r2 = pe.rot90(M, 2)
expected_r2 = np.array([
    [6,5,4],
    [3,2,1]
], dtype=float)
assert np.allclose(r2, expected_r2)

# negative k => e.g. k=-1 => same as k=3
r_neg = pe.rot90(M, -1)
expected_r3 = np.array([
    [3,6],
    [2,5],
    [1,4]
], dtype=float)
assert np.allclose(r_neg, expected_r3)
print("[OK] rot90 tests passed.")

print("\n=== All Tests Done ===")
print("If no error above, MyPyEigen is working correctly!")



=== Test rot90 ===
rot90(M,1)=
 [[4. 1.]
 [5. 2.]
 [6. 3.]]
[OK] rot90 tests passed.

=== All Tests Done ===
If no error above, MyPyEigen is working correctly!


## Test for n-dimension functions

In [3]:
print("\n=== Test ND append (append_nd) ===")
# Set a fixed random seed for reproducibility.
np.random.seed(123)

# Create two 3D arrays with shape (2, 3, 4)
a = np.random.rand(2, 3, 4).astype(np.float64)
b = np.random.rand(2, 3, 4).astype(np.float64)

# Test appending along axis 0: expect shape (2+2, 3, 4) = (4, 3, 4)
r0 = pe.append_nd(a, b, 0)
expected_shape0 = (4, 3, 4)
print("append_nd(a, b, 0) shape =", r0.shape)
assert r0.shape == expected_shape0, "ND append axis 0 shape mismatch"

# Test appending along axis 1: expect shape (2, 3+3, 4) = (2, 6, 4)
r1 = pe.append_nd(a, b, 1)
expected_shape1 = (2, 6, 4)
print("append_nd(a, b, 1) shape =", r1.shape)
assert r1.shape == expected_shape1, "ND append axis 1 shape mismatch"

# Test appending along axis 2: expect shape (2, 3, 4+4) = (2, 3, 8)
r2 = pe.append_nd(a, b, 2)
expected_shape2 = (2, 3, 8)
print("append_nd(a, b, 2) shape =", r2.shape)
assert r2.shape == expected_shape2, "ND append axis 2 shape mismatch"

print("[OK] ND append tests passed.")



=== Test ND append (append_nd) ===
append_nd(a, b, 0) shape = (4, 3, 4)
append_nd(a, b, 1) shape = (2, 6, 4)
append_nd(a, b, 2) shape = (2, 3, 8)
[OK] ND append tests passed.


In [4]:
print("\n=== Test ND concat (concat_nd) ===")
np.random.seed(456)

# Create three 3D arrays with shape (2, 3, 4)
A = np.random.rand(2, 3, 4).astype(np.float64)
B = np.random.rand(2, 3, 4).astype(np.float64)
C = np.random.rand(2, 3, 4).astype(np.float64)

# Test concatenation along axis 0: expect shape (2+2+2, 3, 4) = (6, 3, 4)
r0 = pe.concat_nd([A, B, C], 0)
expected_shape0 = (6, 3, 4)
print("concat_nd([A, B, C], 0) shape =", r0.shape)
assert r0.shape == expected_shape0, "ND concat axis 0 shape mismatch"

# Test concatenation along axis 1: expect shape (2, 3+3+3, 4) = (2, 9, 4)
r1 = pe.concat_nd([A, B, C], 1)
expected_shape1 = (2, 9, 4)
print("concat_nd([A, B, C], 1) shape =", r1.shape)
assert r1.shape == expected_shape1, "ND concat axis 1 shape mismatch"

# Test concatenation along axis 2: expect shape (2, 3, 4+4+4) = (2, 3, 12)
r2 = pe.concat_nd([A, B, C], 2)
expected_shape2 = (2, 3, 12)
print("concat_nd([A, B, C], 2) shape =", r2.shape)
assert r2.shape == expected_shape2, "ND concat axis 2 shape mismatch"

print("[OK] ND concat tests passed.")



=== Test ND concat (concat_nd) ===
concat_nd([A, B, C], 0) shape = (6, 3, 4)
concat_nd([A, B, C], 1) shape = (2, 9, 4)
concat_nd([A, B, C], 2) shape = (2, 3, 12)
[OK] ND concat tests passed.


In [5]:
print("\n=== Test ND stack (stack_nd) ===")
np.random.seed(789)

# For stack_nd, the Python wrapper expects a list of 2D arrays.
# Create three 2D arrays with shape (3, 4)
A = np.random.rand(3, 4).astype(np.float64)
B = np.random.rand(3, 4).astype(np.float64)
C = np.random.rand(3, 4).astype(np.float64)

# Test stacking along a new axis at position 0:
# Each 2D array becomes (1, 3, 4) and stacking 3 arrays gives shape (3, 3, 4)
r0 = pe.stack_nd([A, B, C], 0)
expected_shape0 = (3, 3, 4)
print("stack_nd([A, B, C], 0) shape =", r0.shape)
assert r0.shape == expected_shape0, "ND stack axis 0 shape mismatch"

# Test stacking along a new axis at position 1:
# Each 2D array becomes (3, 1, 4) and stacking 3 arrays gives shape (3, 3, 4)
r1 = pe.stack_nd([A, B, C], 1)
expected_shape1 = (3, 3, 4)
print("stack_nd([A, B, C], 1) shape =", r1.shape)
assert r1.shape == expected_shape1, "ND stack axis 1 shape mismatch"

# Test stacking along a new axis at position 2:
# Each 2D array becomes (3, 4, 1) and stacking 3 arrays gives shape (3, 4, 3)
r2 = pe.stack_nd([A, B, C], 2)
expected_shape2 = (3, 4, 3)
print("stack_nd([A, B, C], 2) shape =", r2.shape)
assert r2.shape == expected_shape2, "ND stack axis 2 shape mismatch"

print("[OK] ND stack tests passed.")
print("\n=== All ND Tests Done ===")



=== Test ND stack (stack_nd) ===
stack_nd([A, B, C], 0) shape = (3, 3, 4)
stack_nd([A, B, C], 1) shape = (3, 3, 4)
stack_nd([A, B, C], 2) shape = (3, 4, 3)
[OK] ND stack tests passed.

=== All ND Tests Done ===
